const ROLES = require("./roles");

module.exports = {
  [ROLES.ADMIN]: ["ALL"],

  [ROLES.COMPANY_OWNER]: [
    "COMPANY_OWNER_DASHBOARD",
    "COMPANY_OWNER_CRUD"
  ],

  [ROLES.VEHICLE_OWNER]: [
    "VEHICLE_OWNER_DASHBOARD",
    "VEHICLE_OWNER_CRUD"
  ],

  [ROLES.SUPPLIER]: [
    "SUPPLIER_OWNER_DASHBOARD",
    "SUPPLIER_OWNER_CRUD"
  ]
};
