// src/constants/permissions.js
export const PERMISSIONS = {
  ADD_SUPPLIER: "ADD_SUPPLIER",
  ADD_COMPANY: "ADD_COMPANY",
  ADD_VEHICLE: "ADD_VEHICLE",

  VIEW_OWN_PROFILE: "VIEW_OWN_PROFILE",

  
  TRIP_CREATE: "TRIP_CREATE",
  TRIP_VIEW: "TRIP_VIEW",
  TRIP_EDIT: "TRIP_EDIT",

  ADVANCE_ADD: "ADVANCE_ADD",

  EXCEL_EXPORT: "EXCEL_EXPORT",

  MASTER_COMPANY_ADD: "MASTER_COMPANY_ADD",
  MASTER_VEHICLE_ADD: "MASTER_VEHICLE_ADD",


  
};
